server:
  port: 8080

spring:
  datasource:
    name: mysql
    url: jdbc:mysql://localhost:3306/lvyou_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**
  resources:
    static-locations: classpath:/css,classpath:/easyui,classpath:/fonts,classpath:/images,classpath:/js,classpath:/plugins,
## 该配置节点为独立的节点，将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.chen.lvyou.entity  # 注意：对应实体类的路径
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# print sql
#logging:
#  level:
#    root: info
#    com.chen: debug
#    org.springframework.security: warn
#    # 默认日志文件名
#    file: log
#    # 默认日志路径
#    path: classpath:/log
#    # logback.xml路径，默认为classpath:logback.xml
#    config: classpath:/logback-spring.xml

logging:
  config: classpath:logback-spring2.xml
  level:
    dao: DEBUG
    org:
      mybatis: DEBUG
    com.chen: DEBUG


